image: docker:18

variables:
  GIT_SSL_NO_VERIFY: 1
  DOCKER_DRIVER: overlay2
  REPOSITORY_HOST: 830055101690.dkr.ecr.us-west-2.amazonaws.com
  REPOSITORY_IMAGE: metal/proton-market
  SERVICE_NAME: proton-market

stages:
  - test
  - build
  - release

test:
  image: nikolaik/python-nodejs
  stage: test
  only:
    - merge_requests
  script:
    - yarn
    - yarn format
    - yarn typecheck
    - yarn lint
    - yarn build

build development:
  stage: build
  only:
    - develop@proton/proton-market
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli yq
  script:
    - export IMAGE=devel-$CI_COMMIT_SHA
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build --no-cache 
      --build-arg NPM_TOKEN=${NPM_TOKEN} 
      --build-arg NEXT_PUBLIC_BLOCK_EXPLORER=${NEXT_PUBLIC_BLOCK_EXPLORER} 
      --build-arg NEXT_PUBLIC_CHAIN_ENDPOINTS=${NEXT_PUBLIC_CHAIN_ENDPOINTS} 
      --build-arg NEXT_PUBLIC_GA_TRACKING_ID=${NEXT_PUBLIC_GA_TRACKING_ID} 
      --build-arg NEXT_PUBLIC_NFT_ENDPOINT=${NEXT_PUBLIC_NFT_ENDPOINT} 
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE

build acceptance:
  stage: build
  only:
    - /^release-.*/@proton/proton-market
  variables:
    DEPLOYMENT_ENVIRONMENT: "PRODUCTION"
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli yq
  script:
    - export IMAGE=$(cat package.json | jq .version -r)
    - $(aws ecr get-login --no-include-email --region us-west-2)
    - docker build --no-cache 
      --build-arg NPM_TOKEN=${NPM_TOKEN} 
      --build-arg NEXT_PUBLIC_BLOCK_EXPLORER=${NEXT_PUBLIC_BLOCK_EXPLORER} 
      --build-arg NEXT_PUBLIC_CHAIN_ENDPOINTS=${NEXT_PUBLIC_CHAIN_ENDPOINTS} 
      --build-arg NEXT_PUBLIC_GA_TRACKING_ID=${NEXT_PUBLIC_GA_TRACKING_ID} 
      --build-arg NEXT_PUBLIC_NFT_ENDPOINT=${NEXT_PUBLIC_NFT_ENDPOINT} 
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker tag $REPOSITORY_IMAGE:latest $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:latest
    - docker push $REPOSITORY_HOST/$REPOSITORY_IMAGE:$IMAGE

update development helm chart:
  image: 830055101690.dkr.ecr.us-west-2.amazonaws.com/metal/ci:latest
  stage: release
  only:
    - develop@proton/proton-market
  script:
    - export IMAGE=devel-$CI_COMMIT_SHA
    - git clone -b develop git@ci.metalpay.network:metalpay/metal-devops.git
    - cd metal-devops/helm/proton
    - touch values-development.yaml
    - cat values-development.yaml | yq '."'$SERVICE_NAME'".image.tag="'$IMAGE'"' -y > new-values.yaml
    - mv -f new-values.yaml values-development.yaml
    - git add values-development.yaml
    - if [[ -z $(git status -s) ]]; then echo 'Tree is clean'; else git commit -m "Update $SERVICE_NAME image tag to $IMAGE"; git push; fi

update acceptance helm chart:
  image: 830055101690.dkr.ecr.us-west-2.amazonaws.com/metal/ci:latest
  stage: release
  only:
    - /^release-.*/@proton/proton-market
  script:
    - export IMAGE=$(cat package.json | jq .version -r)
    - git clone -b develop git@ci.metalpay.network:metalpay/metal-devops.git
    - cd metal-devops/helm/proton
    - touch values-acceptance.yaml
    - cat values-acceptance.yaml | yq '."'$SERVICE_NAME'".image.tag="'$IMAGE'"' -y > new-values.yaml
    - mv -f new-values.yaml values-acceptance.yaml
    - git add values-acceptance.yaml
    - if [[ -z $(git status -s) ]]; then echo 'Tree is clean'; else git commit -m "Update $SERVICE_NAME image tag to $IMAGE"; git push; fi